---
abstract: 'Test JSYNC data'
author:
  - 'Nick Patch <patch@cpan.org>'
  - "Curtis \"Ovid\" Poe <ovid@cpan.org>"
build_requires:
  Test::Tester: 0.107
  ok: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3624'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-JSYNC
provides:
  Test::JSYNC:
    file: lib/Test/JSYNC.pm
    version: 0.01
requires:
  JSYNC: 0
  Test::Differences: 0.47
  Test::Simple: 0.62
  parent: 0
  perl: v5.6.0
resources:
  bugtracker: http://github.com/patch/test-jsync-pm5/issues
  homepage: http://github.com/patch/test-jsync-pm5
  license: http://dev.perl.org/licenses/
  repository: git://github.com/patch/test-jsync-pm5.git
version: 0.01
